// nuxt-app/pages/dashboard.vue
<script setup>
import ProfileHeader from "../components/ProfileHeader.vue";
import RecentActivity from "../components/RecentActivity.vue";
import AccountOverview from "../components/AccountOverview.vue";
</script>

<template>
  <div>
    <ProfileHeader/>

    <div class="mt-8">
      <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <AccountOverview/>
      </div>

      <RecentActivity/>
    </div>
  </div>
</template>

// remix-app/app/routes/dashboard.jsx
import ProfileHeader from "~/components/ProfileHeader";
import AccountOverview from "~/components/AccountOverview";
import RecentActivity from "~/components/RecentActivity";

export default function Dashboard() {
  return (
    <div>
      <ProfileHeader />

      <div className="mt-8">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <AccountOverview />
        </div>

        <RecentActivity />

      </div>
    </div>
  );
}
